### ISSUE TITLE
Honest question about perf

### ISSUE THREAD

**Issue by JSteunou** [goessner/canvas-area#4]
If I understand the concept, this is an html element wrapper around canvas elements. This means you do have to create as much canvas elements as independant *shapes* you want.

How does this perform with a lot of elements versus a single canvas with multiple shapes in ?

**Comment by goessner** [comment]
Yes ... `canvas-area` is a container element for potentially multiple `canvas` elements.

Multiple canvases are mostly used as layers in practice. It is up to you, how you organize, what to draw on which layer. Often there is a *background* layer holding static graphics, which does not need to be updated frequently. In contrast to that there is  is a *dynamic* layer holding animated graphics for instance. There also might be an *interactivity* layer, containing editable geometry.

Separating low frequently updated geometry from high frequently updated geometry by different layers should result in a performance gain.

Creating a canvas for each shape usually won't make sense.

Please note, when using multiple canvases - and stacking them on top of each other:

* For every canvas element except the first one use `position:absolute;` style.
* Stacking level can be made explicite using `z-index: 5;`  style.
* `canvas` elements are transparent by default. So avoid giving them background colors.
* `canvas-area` is managing the *resize*  of its `canvas` children, but not their `redraw`.
*  `canvas-area` is managing the *view* parameters for *pan* and *zoom*, but does not apply those values to the `canvas` contexes. Do that by yourself while redrawing or using the `on('view',...)` handler.

Example:
```
<canvas-area id="ca" width="401" height="301">
    <canvas id="c1" style="position:absolute; z-index:1;"></canvas>
    <canvas id="c2" style="position:absolute; z-index:2;"></canvas>
</canvas-area>
```

**Comment by JSteunou** [comment]
Thank you for this detailed answer, very appreciated!
